"""TestStubGenerator — generate pytest/Jest test stubs from an OpenAPI 3.0 spec."""

from __future__ import annotations

import ast
import logging
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).parent.parent.parent

logger = logging.getLogger(__name__)

PYTEST_SYSTEM_PROMPT = """You are a test engineer. Generate comprehensive pytest test stubs for the given OpenAPI 3.0 spec.

For each operation include:
1. Happy path test (expected 2xx response, valid request body)
2. Not-found test (404 with invalid ID where applicable)
3. Validation error test (422/400 with malformed request body)
4. Unauthorized test (401 with missing/invalid JWT token)
5. One semantically meaningful edge case

Use httpx AsyncClient or requests. Follow pytest conventions:
- async def test_xxx(): for async
- fixtures: @pytest.fixture for client setup
- assert response.status_code == expected
- assert response.json() structure

Output ONLY valid Python code. No markdown fences. No explanations."""

JEST_SYSTEM_PROMPT = """You are a test engineer. Generate comprehensive Jest + supertest test stubs for the given OpenAPI 3.0 spec.

For each operation include:
1. Happy path test (expected 2xx response)
2. Not-found test (404)
3. Validation error test (422/400)
4. Unauthorized test (401 missing token)
5. One edge case

Use axios or node-fetch. Follow Jest conventions:
- describe('OPERATION', () => { it('should ...', ...) })
- beforeAll / afterAll for server setup
- expect(response.status).toBe(expected)

Output ONLY valid JavaScript/ES6 code. No markdown. No explanations."""

# Production-grade pytest template
PYTEST_TEMPLATE = '''"""
Autogenerated test stubs for {api_title}
Generated by speckit-enhanced
"""

import pytest
import httpx
from typing import Dict, Any

BASE_URL = "{base_url}"
AUTH_TOKEN = "test-bearer-token"
HEADERS = {{"Authorization": f"Bearer {{AUTH_TOKEN}}"}}


@pytest.fixture
async def client() -> httpx.AsyncClient:
    """Async HTTP client fixture."""
    async with httpx.AsyncClient(base_url=BASE_URL) as ac:
        yield ac


@pytest.fixture
def auth_headers() -> Dict[str, str]:
    """Authentication headers fixture."""
    return {{"Authorization": f"Bearer {{AUTH_TOKEN}}"}}


{test_functions}
'''

# Test function templates
PYTEST_GET_SUCCESS = '''
@pytest.mark.asyncio
async def test_{op_id_safe}_success(client: httpx.AsyncClient):
    """Test successful GET {path}."""
    response = await client.get("{path}")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, dict)
'''

PYTEST_POST_SUCCESS = '''
@pytest.mark.asyncio
async def test_{op_id_safe}_success(client: httpx.AsyncClient):
    """Test successful POST {path}."""
    payload = {{}}
    response = await client.post("{path}", json=payload)
    assert response.status_code in (200, 201)
    data = response.json()
    assert isinstance(data, dict)
'''

PYTEST_NOT_FOUND = '''
@pytest.mark.asyncio
async def test_{op_id_safe}_not_found(client: httpx.AsyncClient):
    """Test 404 when resource does not exist."""
    response = await client.{method}("{not_found_path}")
    assert response.status_code == 404
'''

PYTEST_UNAUTHORIZED = '''
@pytest.mark.asyncio
async def test_{op_id_safe}_unauthorized(client: httpx.AsyncClient):
    """Test 401 when no auth token provided."""
    response = await client.{method}("{path}", headers={{{{}}}})
    assert response.status_code == 401
'''

PYTEST_VALIDATION_ERROR = '''
@pytest.mark.asyncio
async def test_{op_id_safe}_validation_error(client: httpx.AsyncClient):
    """Test 422 with malformed request body."""
    invalid_payload = {{"invalid": "data"}}
    response = await client.{method}("{path}", json=invalid_payload)
    assert response.status_code in (400, 422)
'''

# Production-grade Jest template
JEST_TEMPLATE = '''/**
 * Autogenerated test stubs for {api_title}
 * Generated by speckit-enhanced
 */

import {{ createClient }} from '@axios/client';
import {{ describe, it, expect, beforeAll, afterAll }} from '@jest/globals';

const BASE_URL = '{base_url}';
const AUTH_TOKEN = 'test-bearer-token';

let client;

beforeAll(async () => {{
  client = createClient({{
    baseURL: BASE_URL,
    headers: {{
      'Authorization': `Bearer ${{AUTH_TOKEN}}`,
    }},
  }});
}});

afterAll(async () => {{
  if (client) {{
    await client.close();
  }}
}});

{test_functions}
'''

JEST_GET_SUCCESS = """
describe('GET {path}', () => {{
  it('should return successful response', async () => {{
    const response = await client.get('{path}');
    expect(response.status).toBe(200);
    expect(response.data).toBeDefined();
  }});
}});
"""

JEST_POST_SUCCESS = """
describe('POST {path}', () => {{
  it('should create resource successfully', async () => {{
    const payload = {{}};
    const response = await client.post('{path}', payload);
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
    expect(response.data).toBeDefined();
  }});
}});
"""

JEST_NOT_FOUND = """
describe('{method.upper()} {path} - Not Found', () => {{
  it('should return 404 for non-existent resource', async () => {{
    const response = await client.{method}('{not_found_path}');
    expect(response.status).toBe(404);
  }});
}});
"""

JEST_UNAUTHORIZED = """
describe('{method.upper()} {path} - Unauthorized', () => {{
  it('should return 401 without auth token', async () => {{
    const response = await client.{method}('{path}', {{
      headers: {{}},
    }});
    expect(response.status).toBe(401);
  }});
}});
"""

JEST_VALIDATION_ERROR = """
describe('{method.upper()} {path} - Validation Error', () => {{
  it('should return 422 with invalid payload', async () => {{
    const invalidPayload = {{ invalid: 'data' }};
    const response = await client.{method}('{path}', invalidPayload);
    expect(response.status).toBeGreaterThanOrEqual(400);
    expect(response.status).toBeLessThan(500);
  }});
}});
"""



class TestStubGenerator:
    """
    Generates pytest and Jest test stubs from a validated OpenAPI 3.0 spec.

    Primary: LLM-generated stubs with edge case expansion.
    Fallback: Jinja2 template-based stubs.
    """

    def __init__(self):
        self._llm = None

    def _get_llm(self):
        if self._llm is None:
            import sys
            sys.path.insert(0, str(ROOT))
            from tools.llm_client import UnifiedLLMClient
            self._llm = UnifiedLLMClient()
        return self._llm

    async def generate(self, spec: dict, framework: str = "both", base_url: str = "http://localhost") -> dict:
        """
        Generate test stubs for a validated OpenAPI spec.

        Args:
            spec: Parsed OpenAPI 3.0 dict
            framework: "pytest" | "jest" | "both"
            base_url: Server base URL

        Returns:
            dict: pytest_stubs, jest_stubs, test_count, operations_covered
        """
        import yaml
        spec_yaml = yaml.dump(spec, sort_keys=False, allow_unicode=True)
        if len(spec_yaml) > 12000:
            spec_yaml = spec_yaml[:12000] + "\n# ... (truncated)"

        paths = spec.get("paths") or {}
        operations = self._count_operations(paths)

        pytest_stubs = None
        jest_stubs = None
        test_count = 0

        if framework in ("pytest", "both"):
            pytest_stubs = await self._generate_pytest(spec_yaml, base_url)
            if not self._is_valid_python(pytest_stubs):
                logger.warning("LLM pytest stubs failed syntax check; using template")
                pytest_stubs = self._pytest_template(spec, base_url)
            test_count += self._count_tests_in_python(pytest_stubs)

        if framework in ("jest", "both"):
            jest_stubs = await self._generate_jest(spec_yaml, base_url)
            if not jest_stubs or not self._is_valid_jest(jest_stubs):
                logger.warning("LLM Jest stubs failed syntax check; using template")
                jest_stubs = self._jest_template(spec, base_url)
            test_count += self._count_tests_in_jest(jest_stubs)

        if framework in ("jest", "both"):
            jest_stubs = await self._generate_jest(spec_yaml, base_url)
            test_count += self._count_tests_in_jest(jest_stubs)

        return {
            "pytest_stubs": pytest_stubs,
            "jest_stubs": jest_stubs,
            "test_count": test_count,
            "operations_covered": operations,
        }

    async def _generate_pytest(self, spec_yaml: str, base_url: str) -> str:
        user_msg = f"Base URL: {base_url}\n\nSpec:\n{spec_yaml}"
        try:
            code = await self._get_llm().complete(
                system=PYTEST_SYSTEM_PROMPT,
                user=user_msg,
                task="test_stub_generation",
                max_tokens=5000,
            )
            return self._strip_fences(code)
        except Exception as e:
            logger.error("pytest generation failed: %s", e)
            return f"# LLM generation failed: {e}\n\nimport pytest\n\n# TODO: Add tests manually\n"

    async def _generate_jest(self, spec_yaml: str, base_url: str) -> str:
        user_msg = f"Base URL: {base_url}\n\nSpec:\n{spec_yaml}"
        try:
            code = await self._get_llm().complete(
                system=JEST_SYSTEM_PROMPT,
                user=user_msg,
                task="test_stub_generation",
                max_tokens=5000,
            )
            return self._strip_fences(code)
        except Exception as e:
            logger.error("Jest generation failed: %s", e)
            return f"// LLM generation failed: {e}\n\ndescribe('API', () => {{\n  // TODO: Add tests manually\n}});\n"

    def _pytest_template(self, spec: dict, base_url: str) -> str:
        """Production-grade template for pytest stubs."""
        test_functions = []
        paths = spec.get("paths") or {}
        api_title = (spec.get("info") or {}).get("title", "API")

        for path, path_item in paths.items():
            if not isinstance(path_item, dict):
                continue
            for method, op in path_item.items():
                if not isinstance(op, dict) or method.startswith("x-"):
                    continue

                op_id = op.get("operationId") or f"{method}_{path.strip('/').replace('/', '_')}"
                op_id_safe = op_id.replace("-", "_").replace("/", "_").replace(".", "_")
                responses = op.get("responses") or {}
                success_code = next((k for k in responses if str(k).startswith("2")), "200")

                # Happy path test
                if method == "get":
                    test_functions.append(PYTEST_GET_SUCCESS.format(
                        op_id_safe=op_id_safe, path=path
                    ))
                elif method == "post":
                    test_functions.append(PYTEST_POST_SUCCESS.format(
                        op_id_safe=op_id_safe, path=path
                    ))
                else:
                    test_functions.append(f'''
@pytest.mark.asyncio
async def test_{op_id_safe}_success(client: httpx.AsyncClient):
    """Test successful {method.upper()} {path}."""
    response = await client.{method}("{path}")
    assert response.status_code == {success_code}
    data = response.json()
    assert isinstance(data, dict)
''')

                # Not found test (for paths with IDs)
                if "/{" in path:
                    not_found_path = path.split("/{")[0] + "/999999"
                    test_functions.append(PYTEST_NOT_FOUND.format(
                        op_id_safe=op_id_safe,
                        method=method,
                        path=path,
                        not_found_path=not_found_path,
                    ))

                # Unauthorized test
                test_functions.append(PYTEST_UNAUTHORIZED.format(
                    op_id_safe=op_id_safe,
                    method=method,
                    path=path,
                ))

                # Validation error test (for POST/PUT/PATCH)
                if method in ("post", "put", "patch"):
                    test_functions.append(PYTEST_VALIDATION_ERROR.format(
                        op_id_safe=op_id_safe,
                        method=method,
                        path=path,
                    ))

        return PYTEST_TEMPLATE.format(
            api_title=api_title,
            base_url=base_url,
            test_functions="".join(test_functions),
        )

    def _count_operations(self, paths: dict) -> int:
        count = 0
        for path_item in paths.values():
            if isinstance(path_item, dict):
                for method in ("get", "post", "put", "patch", "delete"):
                    if isinstance(path_item.get(method), dict):
                        count += 1
        return count

    def _is_valid_python(self, code: str) -> bool:
        if not code:
            return False
        try:
            ast.parse(code)
            return True
        except SyntaxError:
            return False

    def _count_tests_in_python(self, code: str) -> int:
        if not code:
            return 0
        return code.count("def test_")

    def _jest_template(self, spec: dict, base_url: str) -> str:
        """Production-grade template for Jest stubs."""
        test_functions = []
        paths = spec.get("paths") or {}
        api_title = (spec.get("info") or {}).get("title", "API")

        for path, path_item in paths.items():
            if not isinstance(path_item, dict):
                continue
            for method, op in path_item.items():
                if not isinstance(op, dict) or method.startswith("x-"):
                    continue

                op_id = op.get("operationId") or f"{method}_{path.strip('/').replace('/', '_')}"

                # Happy path test
                if method == "get":
                    test_functions.append(JEST_GET_SUCCESS.format(path=path))
                elif method == "post":
                    test_functions.append(JEST_POST_SUCCESS.format(path=path))
                else:
                    test_functions.append(f"""
describe('{method.upper()} {path}', () => {{
  it('should return successful response', async () => {{
    const response = await client.{method}('{path}');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  }});
}});
""")

                # Not found test
                if "/{" in path:
                    not_found_path = path.split("/{")[0] + "/999999"
                    test_functions.append(JEST_NOT_FOUND.format(
                        method=method,
                        path=path,
                        not_found_path=not_found_path,
                    ))

                # Unauthorized test
                test_functions.append(JEST_UNAUTHORIZED.format(
                    method=method,
                    path=path,
                ))

                # Validation error test
                if method in ("post", "put", "patch"):
                    test_functions.append(JEST_VALIDATION_ERROR.format(
                        method=method,
                        path=path,
                    ))

        return JEST_TEMPLATE.format(
            api_title=api_title,
            base_url=base_url,
            test_functions="".join(test_functions),
        )

    def _count_tests_in_jest(self, code: str) -> int:
        if not code:
            return 0
        return code.count("it(") + code.count("it.todo(") + code.count("test(")

    def _is_valid_jest(self, code: str) -> bool:
        """Basic JavaScript syntax validation."""
        if not code:
            return False
        # Check for basic JS syntax errors
        try:
            # Count brackets/parentheses
            open_braces = code.count("{")
            close_braces = code.count("}")
            open_parens = code.count("(")
            close_parens = code.count(")")
            if open_braces != close_braces or open_parens != close_parens:
                return False
            # Check for describe/it blocks
            if "describe" not in code or "it" not in code:
                return False
            return True
        except Exception:
            return False

    def _strip_fences(self, text: str) -> str:
        text = text.strip()
        if text.startswith("```"):
            lines = text.split("\n")
            start, end = 1, len(lines)
            for i in range(len(lines) - 1, 0, -1):
                if lines[i].strip() == "```":
                    end = i
                    break
            text = "\n".join(lines[start:end])
        return text
